  server:
    port: 8082

  spring:
    datasource:
      url: jdbc:sqlserver://10.10.90.59:1433;databaseName=KPCB_SWITCH_03012023;encrypt=true;trustServerCertificate=true;
      username: sa
      password : Turing_2@!2
      driver-class-name : com.microsoft.sqlserver.jdbc.SQLServerDriver
    application:
      name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.SQLServer2012Dialect

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka